### ISSUE TITLE
Provide a working "hello-world" example

### ISSUE THREAD

**Issue by jangalinski** [smartics/smartics-jboss-modules-maven-plugin#23]
I really would like to try this plugin. But I cannot get it to work. The documentation is incompatible to the releases on mvn-central and I did'nt find which repository to add.
Also, what is a plausible (minimal) setup to choose when configuring this plugin? Could someone enlighten me?

**Comment by RobertReiner** [comment]
We haven't released the plugin on Maven Central, yet (AFAIK :)). Here is the info on how to configure the Maven environment to access the artifacts from the smartics repo: https://www.smartics.eu/confluence/display/HOMESPACE/Accessing+Artifacts

On https://www.smartics.eu/confluence/display/SJBMMP/smartics+JBoss+Modules+Maven+Plugin you can find examples on how to configure the plugin, especially:
* https://www.smartics.eu/confluence/display/SJBMMP/Usage+Modules
* https://www.smartics.eu/confluence/display/SJBMMP/smartics+JBoss+Modules+Maven+Plugin
* https://www.smartics.eu/confluence/display/SJBMMP/Import+Module+Descriptors

Note that the V2-Schema is currently experimental and there is no documentation for it (besides the unit tests the team supporting this version has written).

**Comment by jangalinski** [comment]
Thanks for the answer, I will look into it. regarding mvn-central: there are artefacts available: http://mvnrepository.com/artifact/org.fusesource.mvnplugins/smartics-jboss-modules-maven-plugin but I didn't get them to work (and they have a different groupId than the documentation).

**Comment by RobertReiner** [comment]
You are welcome! Hope it helps! If you have questions - or hints on how to improve the documentation ;) - please send us a note!

The artifact on mvn-central is certainly due to the fact that we still fail in providing an artifact by ourselves ...

BTW: Here is a live example where James and Thomas use the plugin: https://github.com/wildfly-extras/wildfly-camel (they probably use the V2 format I'm not familiar with, though)
