### ISSUE TITLE
Smartics + Multi artifact version

### ISSUE THREAD

**Issue by malys** [smartics/smartics-jboss-modules-maven-plugin#33]
Hello,
First of all, I want to thank you for developing this plugin.
I'm trying to generate the JBoss module distribution for JBoss AS7 server.
We deploye different ear on this machine. Each application uses some modules and sometimes the same but with different version.

* My first strategy was to generate modules distribution launching smartics-jb-m one time.
I cumulate all artifact in a specific pom and your plugin will generate the distribution.
In this case, I can't resolve this situation:

```xml
<dependencyManagement>
   <dependencies>
           <dependency> // version for the first ear
               <groupId>org.json</groupId>
               <artifactId>json</artifactId>
               <version>20150729</version>
           </dependency>
           <dependency>  // version for the second
               <groupId>org.json</groupId>
               <artifactId>json</artifactId>
               <version>20080701</version>
           </dependency>
...
```

```bash
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.json:json:jar -> version 20150729 vs 20080701 @ com.lyra.tmp:jbosslyra:[unknown-version]
```
PRO: quick, generate JBoss module for a server (JBoss module philosophy)
CONS: same artifact with different version: failed

* The second strategy will be to generate a distribution for  each application and merge them
PRO: same artifact with different version: solved
CONS: Slow, add merge step in the process (override issue?)

Please, could you advice me?  I prefer the first one but have you any idea to resolve my issue?

Thanks,

**Comment by RobertReiner** [comment]
Hi Malys,

thank you for your feedback!

I'm not sure if I understand your requirements deeply enough to support you via this communication channel :). Typically supporting product lines with dependencies of different versions is not a trivial task. Each project has different drivers and constraints. For instance: If you release your EARs on internal servers only, you are riding a completely different wave as if your product is installed by a hundred of customers. Therefore there are different solutions to the problem. Nevertheless here are some points that may help you to find your solution to your problem ...

Fist of all: our plugin's purpose is to map information from a Maven POM to JBoss Modules. Use cases where there are dependencies in different versions are (theoretically) supported as long as the solution can be specified in a valid POM. I say 'theoretically' because there are use cases we did not think of in first place. Some of them have been reported and we fixed them or added the necessary new features.

Having the same artifact in different version in the dependency management block is - at least to my knowledge - not a valid approach. Maven should resolve the artifact to the latest version. So it won't help to add multiple dependencies this way. Here is more information to this on [StackOverflow](http://stackoverflow.com/questions/24962607/multiple-versions-of-the-same-dependency-in-maven).

When I needed to support modules in different versions in the past, I handled these dependencies independent of the applications (EARs). For instance I had a library doing exception handling and this library has been in its own release cycle and different versions have been provided as modules. The EARs than simply pick the version they need at build time and get them supplied on JBoss at runtime.

From the EAR's perspective: If I need to support a bunch of dependencies with different versions I'd suggest to define a BOM ([Bill-of-Materials](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)). Then different EARs may select the version of the BOM that is most appropriate for them. Think of a set of dependencies known to work well together. This BOM project may then be deployed as a module. If this is leading into combinatorial hell (because you have to support a large number of artifacts in different versions) then you need to provide each module in its own version - as in my library example with the exceptions. Each EAR has to pick those that work for them manually.

So: I do not think their are any generic short cuts. There may be trade-offs you think fair enough for you specific requirements. Otherwise I would suggest - and I want to strain the possibility that I misunderstood your context completely - to separate the EAR from the modules and define a releasing process for them independently.

Hope this helps ... :)

Kind regard,

Robert
