### ISSUE TITLE
Provide an initial release

### ISSUE THREAD

**Issue by tdiesler** [smartics/smartics-jboss-modules-maven-plugin#8]
There are currently no tags/releases associated with this project

**Comment by RobertReiner** [comment]
We had no release since our move from SVN to GitHub.

Our site documentation references the versions and there you can find the link to the old SVN repository.

For instance version 2.0.0: https://www.smartics.eu/de.smartics.maven.plugin/smartics-jboss-modules-maven-plugin/2.0.0/index.html

On the top "project documentation" -> Information Systems -> Source Repository.

And here is the tag:
https://www.smartics.eu/svn/public/maven/smartics-jboss-modules-maven-plugin/tags/smartics-jboss-modules-maven-plugin-2.0.0/

We will resolve this with our next release so that users can find tagged versions as they are expecting. In the meantime I hope this is a workaround that is good enough ... :)

**Comment by tdiesler** [comment]
If your move to github includes project history, you should also recreate tags IMHO.

Moving forward I personally don't care much about past history - just wanted to have a stabe tag to build from. If #10 makes it upstream, I can use master

**Comment by tdiesler** [comment]
2.0.1 is there
